runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
  
#Endpoints Handler

# - url: /api/.*
- url: /_ah/spi/.*
  script: api.app

#Main Handler
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: endpoints
  version: 1.0
# - name: pycrypto
#   version: 2.6
# - name: ssl
#   version: 2.7.11