runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

#- url: /apis/.*
#  script: main.apis

#Main Handler
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: endpoints
  version: 1.0