runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
- url: /style\.css
  static_files: style.css
  upload: style\.css

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest