#application: theatre-management
#version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /stylesheets
  static_dir: stylesheets
  
#Endpoints Handler
- url: /_ah/spi/.*
  script: api.app

#Main Handler
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest